# Autogenerated file
def render(detected_plates_history):
    yield """<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <title>Title</title>
    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">
</head>
<body>
  <div class=\"container bg-white\">
    <h1 class=\"text-center pt-5\">Detection history</h1>
    <br>
    <h4 class=\"text-center pb-5\"><a href=\"/allowed_plates\">Allowed license plates list</a></h4>
    <br>
    <table class=\"table\">
      <thead class=\"\">
        <tr>
          <th scope=\"col\">Date</th>
          <th scope=\"col\">Plate</th>
          <th scope=\"col\" class=\"text-end\">Authorized</th>
          <th scope=\"col\" class=\"text-end\">Add to authorized</th>
        </tr>
      </thead>

      """
    for detected_plate in detected_plates_history:
        yield """      <tr>
        <td>"""
        yield str(detected_plate[1])
        yield """</td>
        <td>"""
        yield str(detected_plate[0])
        yield """</td>
        <td class=\"text-end\">"""
        yield str(detected_plate[2])
        yield """</td>
        <td class=\"text-end\">
          <form action=\"/allowed_plates/add\" method=\"post\">
            <input value=\""""
        yield str(detected_plate[0])
        yield """\" name=\"plate\" hidden/>
            <button class=\"btn btn-outline-success\" type=\"submit\">Authorize</button>
          </form>
        </td>
      </tr>
      """
    yield """    </table>
  </div>

</body>
</html>"""
